// 理科クイズ の問題データ
// ROUND_1 は「範囲を選ぶ」フィルタに使うラベル。今回は分けずに全問同じラベルにしている。
//
// category は学習カレンダー（date × category のマトリクス）の列に直接使われる。
//
// 画像対応（science単元の拡張）:
// - questionImage: 問題文の上に表示する図（'images/xxx.png'）。省略可。
// - choices: 通常は文字列だが、'images/xxx.png' のような画像パスを入れると
//   選択肢が画像ボタンとして表示される（index.html側で拡張子を見て自動判定）。
// - answer: choicesの中の1つと一致する値（画像パスの場合は画像パス自体）。
// - answerLabel: answerが画像パスのとき、正誤フィードバックに表示する人が読める説明文。
const ROUND_1 = '基本';
const ROUND_2 = '4年上15回（2026/6組分けテスト③）';

const QUESTIONS = [
  {
    id: 'science-01',
    round: ROUND_1,
    category: '天気',
    question: '冬のころの日本の天気の説明として正しいものはどれですか。',
    answer: '日本海側では降水量が多くなり、太平洋側ではかんそうした日が続く。',
    choices: [
      '日本海側では降水量が多くなり、太平洋側ではかんそうした日が続く。',
      '東西に長く雲の帯ができ、広い地域で長い雨やくもりの日が続く。',
      '3〜4日ごとに晴れの日と天気の悪い日がくり返される。',
      '全国的に晴れの日が多くなるが、夕立が降ることも多い。',
    ],
  },
  {
    id: 'science-02',
    round: ROUND_1,
    category: '天気',
    question: '梅雨のころの日本の天気の説明として正しいものはどれですか。',
    answer: '東西に長く雲の帯ができ、広い地域で長い雨やくもりの日が続く。',
    choices: [
      '東西に長く雲の帯ができ、広い地域で長い雨やくもりの日が続く。',
      '日本海側では降水量が多くなり、太平洋側ではかんそうした日が続く。',
      '3〜4日ごとに晴れの日と天気の悪い日がくり返される。',
      '全国的に晴れの日が多くなるが、夕立が降ることも多い。',
    ],
  },
  {
    id: 'science-03',
    round: ROUND_1,
    category: '天気',
    question: '夏のころの日本の天気の説明として正しいものはどれですか。',
    answer: '全国的に晴れの日が多くなるが、夕立が降ることも多い。',
    choices: [
      '全国的に晴れの日が多くなるが、夕立が降ることも多い。',
      '東西に長く雲の帯ができ、広い地域で長い雨やくもりの日が続く。',
      '日本海側では降水量が多くなり、太平洋側ではかんそうした日が続く。',
      '3〜4日ごとに晴れの日と天気の悪い日がくり返される。',
    ],
  },
  {
    id: 'science-04',
    round: ROUND_1,
    category: '天気',
    question: '春のころの日本の天気の説明として正しいものはどれですか。',
    answer: '3〜4日ごとに晴れの日と天気の悪い日がくり返される。',
    choices: [
      '3〜4日ごとに晴れの日と天気の悪い日がくり返される。',
      '全国的に晴れの日が多くなるが、夕立が降ることも多い。',
      '東西に長く雲の帯ができ、広い地域で長い雨やくもりの日が続く。',
      '日本海側では降水量が多くなり、太平洋側ではかんそうした日が続く。',
    ],
  },
  {
    id: 'science-05',
    round: ROUND_1,
    category: '地層',
    question: 'どろ・大きいつぶの砂・小さいつぶの砂を混ぜて水に入れてよくかき混ぜたあと、静かに置いておくと、下から順にどのように積もりますか。',
    answer: '大きいつぶの砂 → 小さいつぶの砂 → どろ',
    choices: [
      '大きいつぶの砂 → 小さいつぶの砂 → どろ',
      'どろ → 小さいつぶの砂 → 大きいつぶの砂',
      '小さいつぶの砂 → 大きいつぶの砂 → どろ',
      'どろ → 大きいつぶの砂 → 小さいつぶの砂',
    ],
  },
  {
    id: 'science-06',
    round: ROUND_1,
    category: 'こん虫',
    question: 'さなぎの時期がない育ち方（不完全変態）をする昆虫はどれですか。',
    answer: 'アキアカネ',
    choices: ['アキアカネ', 'ナナホシテントウ', 'ミツバチ', 'カブトムシ'],
  },
  {
    id: 'science-07',
    round: ROUND_1,
    category: 'こん虫',
    question: 'さなぎの時期がある育ち方（完全変態）をする昆虫はどれですか。',
    answer: 'ナナホシテントウ',
    choices: ['ナナホシテントウ', 'アキアカネ', 'バッタ', 'セミ'],
  },
  {
    id: 'science-08',
    round: ROUND_1,
    category: '磁石',
    question: '棒磁石を真ん中で半分に切ると、切り口にはそれぞれ何極ができますか。',
    answer: '両方の切り口に新しくN極とS極ができる',
    choices: [
      '両方の切り口に新しくN極とS極ができる',
      '切り口にはN極だけができる',
      '切り口にはS極だけができる',
      '磁石の性質がなくなり、極はできなくなる',
    ],
  },
  {
    id: 'science-09',
    round: ROUND_1,
    category: '磁石',
    question: '磁石を近づけていないとき、方位磁針のN極が指す方角はどこですか。',
    answer: '北',
    choices: ['北', '南', '東', '西'],
  },
  {
    id: 'science-10',
    round: ROUND_1,
    category: '春の生物',
    question: 'オオイヌノフグリと同じように、外国から人の手によって運ばれ、日本でふえた植物（帰化植物）はどれですか。',
    answer: 'シロツメクサ',
    choices: ['シロツメクサ', 'ナズナ', 'スミレ', 'ハコベ'],
  },
  {
    id: 'science-11',
    round: ROUND_1,
    category: '春の生物',
    question: 'ジンチョウゲのように樹木にさく花ではないものはどれですか。',
    answer: 'スイセン',
    choices: ['スイセン', 'ウメ', 'ツツジ', 'モクレン'],
  },
  {
    id: 'science-12',
    round: ROUND_1,
    category: '春の生物',
    question: '池で見つけたヒキガエルの卵のそばに、親ガエルのすがたが見られなかったのはなぜだと考えられますか。',
    answer: '冬眠していて、春に目覚めて産卵したあと、再びねむってしまうから。',
    choices: [
      '冬眠していて、春に目覚めて産卵したあと、再びねむってしまうから。',
      '冬眠していて、春に目覚めて産卵すると、役目を終えて死んでしまうから。',
      '秋に産卵したあと、冬から春にかけてはずっと冬眠しているから。',
      '秋に産卵すると、役目を終えて死んでしまうから。',
    ],
  },
  {
    id: 'science-13',
    round: ROUND_1,
    category: '春の生物',
    question: 'ツバメのように、春に南の国からわたってきて日本で子育てをし、秋にまた南の国へわたっていく鳥を何といいますか。',
    answer: '夏鳥',
    choices: ['夏鳥', '冬鳥', '留鳥', '漂鳥'],
  },
  {
    id: 'science-14',
    round: ROUND_1,
    category: '春の生物',
    question: '次のうち、ツバメと同じ「夏鳥」に分類される鳥はどれですか。',
    answer: 'カッコウ',
    choices: ['カッコウ', 'マガモ', 'ウグイス', 'キジバト'],
  },
  {
    id: 'science-15',
    round: ROUND_1,
    category: '太陽の動き',
    question: '太陽が真南に来ることを、太陽の何といいますか。',
    answer: '南中',
    choices: ['南中', '日周運動', '天頂通過', '正中線'],
  },
  {
    id: 'science-16',
    round: ROUND_1,
    category: '太陽の動き',
    question: '一年のうちで、太陽の南中高度が最も高くなるのはいつですか。',
    answer: '夏至',
    choices: ['夏至', '冬至', '春分', '秋分'],
  },
  {
    id: 'science-17',
    round: ROUND_1,
    category: '太陽の動き',
    question: '一年のうちで、太陽の南中高度が最も低くなるのはいつですか。',
    answer: '冬至',
    choices: ['冬至', '夏至', '春分', '秋分'],
  },
  {
    id: 'science-18',
    round: ROUND_1,
    category: '太陽の動き',
    question: '春分・秋分の日の太陽の南中高度は、夏至と冬至の高度と比べるとどうなっていますか。',
    answer: '夏至と冬至のちょうど中間くらいになる',
    choices: [
      '夏至と冬至のちょうど中間くらいになる',
      '夏至とほぼ同じ高さになる',
      '冬至とほぼ同じ高さになる',
      '夏至より高くなる',
    ],
  },
  {
    id: 'science-19',
    round: ROUND_1,
    category: '水のすがた',
    question: '水がふっとうする温度は何℃ですか。',
    answer: '100℃',
    choices: ['100℃', '0℃', '4℃', '120℃'],
  },
  {
    id: 'science-20',
    round: ROUND_1,
    category: '水のすがた',
    question: '水がふっとうする温度のことを、特に何といいますか。',
    answer: '沸点',
    choices: ['沸点', '融点', '凝固点', '露点'],
  },
  {
    id: 'science-21',
    round: ROUND_1,
    category: '水のすがた',
    question: '氷がとけて水になる温度のことを、特に何といいますか。',
    answer: '融点',
    choices: ['融点', '沸点', '凝固点', '露点'],
  },
  {
    id: 'science-22',
    round: ROUND_1,
    category: '水のすがた',
    question: '水を加熱してふっとうさせたとき、目に見えない気体になって出てくるものを何といいますか。',
    answer: '水蒸気',
    choices: ['水蒸気', 'ゆげ', 'ちっ素', '二酸化炭素'],
  },
  {
    id: 'science-23',
    round: ROUND_1,
    category: '水のすがた',
    question: '同じ重さの水を固体・液体・気体で比べたとき、体積が最も小さくなるのはどのすがたのときですか。',
    answer: '液体',
    choices: ['液体', '固体', '気体', 'どれも同じ体積になる'],
  },
  {
    id: 'science-24',
    round: ROUND_1,
    category: '光',
    question: '光が鏡などにあたって、はね返って向きを変える性質を何といいますか。',
    answer: '光の反射',
    choices: ['光の反射', '光の直進', '光の屈折', '光の分散'],
  },
  {
    id: 'science-25',
    round: ROUND_1,
    category: '光',
    question: '光が水やガラスなど性質のちがうものの中に進むとき、境目で折れ曲がる性質を何といいますか。',
    answer: '光の屈折',
    choices: ['光の屈折', '光の直進', '光の反射', '光の分散'],
  },
  {
    id: 'science-26',
    round: ROUND_1,
    category: '光',
    question: '虫めがねなどのレンズの中心から、光が１点に集まる点までの距離を何といいますか。',
    answer: '焦点距離',
    choices: ['焦点距離', '反射距離', '屈折率', '集光点'],
  },
  {
    id: 'science-27',
    round: ROUND_1,
    category: '光',
    question: '虫めがねを通った太陽の光が１点に集まってできる、非常に明るく熱くなる点のことを何といいますか。',
    answer: '焦点',
    choices: ['焦点', '頂点', '反射点', '中心点'],
  },
  {
    id: 'science-28',
    round: ROUND_1,
    category: '磁石',
    questionImage: 'images/mag-fig1.png',
    question: '（図）のように、ゴム磁石のまわりのAの位置に方位磁針を置くと、針はどのようになりますか。方位磁針の絵は、どれも上が北の向きです。',
    answer: 'images/mag-choice-w.png',
    answerLabel: 'N極が西を向く',
    choices: [
      'images/mag-choice-n.png',
      'images/mag-choice-e.png',
      'images/mag-choice-s.png',
      'images/mag-choice-w.png',
    ],
  },
  {
    id: 'science-29',
    round: ROUND_1,
    category: '磁石',
    questionImage: 'images/mag-fig1.png',
    question: '同じ（図）で、Bの位置に方位磁針を置くと、針はどのようになりますか。方位磁針の絵は、どれも上が北の向きです。',
    answer: 'images/mag-choice-e.png',
    answerLabel: 'N極が東を向く',
    choices: [
      'images/mag-choice-n.png',
      'images/mag-choice-e.png',
      'images/mag-choice-s.png',
      'images/mag-choice-w.png',
    ],
  },
  {
    id: 'science-30',
    round: ROUND_1,
    category: '磁石',
    questionImage: 'images/mag-fig2.png',
    question: '（図）のように、ゴム磁石を真ん中で半分に切り、その間のCの位置に方位磁針を置くと、針はどのようになりますか。方位磁針の絵は、どれも上が北の向きです。',
    answer: 'images/mag-choice-w.png',
    answerLabel: 'N極が西を向く',
    choices: [
      'images/mag-choice-n.png',
      'images/mag-choice-e.png',
      'images/mag-choice-s.png',
      'images/mag-choice-w.png',
    ],
  },
  {
    id: 'science-31',
    round: ROUND_1,
    category: '太陽の動き',
    question: '日の入りのときの、地平線と太陽の位置関係を正しく表している図はどれですか。',
    answer: 'images/sun-sunset-b.png',
    answerLabel: '太陽が地平線に半分だけ沈みかけているすがた',
    choices: [
      'images/sun-sunset-a.png',
      'images/sun-sunset-b.png',
      'images/sun-sunset-c.png',
      'images/sun-sunset-d.png',
    ],
  },
  {
    id: 'science-32',
    round: ROUND_1,
    category: '太陽の動き',
    questionImage: 'images/sun-fig1.png',
    question: '（図）は東京で観測した太陽の通り道を表したもので、あ・い・うは春分・夏至・冬至のいずれかの日の記録です。冬至の日の記録を示しているのはどれですか。',
    answer: 'う',
    choices: ['う', 'あ', 'い', '資料だけでは決められない'],
  },
  {
    id: 'science-33',
    round: ROUND_1,
    category: '太陽の動き',
    questionImage: 'images/sun-fig1.png',
    question: '5月のある日、太陽の南中高度は日に日に高くなっていました（夏至が近づいている）。この日の太陽の通り道は、（図）のどこを通りますか。',
    answer: 'あといの間',
    choices: ['あといの間', 'あの外側', 'いとうの間', 'うの内側'],
  },
  {
    id: 'science-34',
    round: ROUND_1,
    category: '太陽の動き',
    questionImage: 'images/sun-shadow-fig2.png',
    question: '（図）のように地面に8方位をかき、棒を垂直に立てて影のようすを観察しました。この影のようすから、このとき太陽はどの方角にありますか。',
    answer: '南東',
    choices: ['南東', '北西', '北東', '南西'],
  },
  {
    id: 'science-35',
    round: ROUND_1,
    category: '太陽の動き',
    questionImage: 'images/sun-shadow-fig2.png',
    question: '同じ（図）の観察を行った時間帯は、次のうちどれですか。',
    answer: '午前',
    choices: ['午前', '午後', '正午', '真夜中'],
  },
  {
    id: 'science-36',
    round: ROUND_1,
    category: '光',
    questionImage: 'images/light-fig1.png',
    question: '（図）のように、光源装置を使って鏡の点Pに細い光をあてると、光ははね返って矢印のように進みました。角あ〜えのうち、入射角を示しているのはどれですか。',
    answer: 'い',
    choices: ['い', 'あ', 'う', 'え'],
  },
  {
    id: 'science-37',
    round: ROUND_1,
    category: '光',
    questionImage: 'images/light-fig1.png',
    question: '同じ（図）で、反射角を示しているのはどれですか。',
    answer: 'う',
    choices: ['う', 'あ', 'い', 'え'],
  },
  {
    id: 'science-38',
    round: ROUND_1,
    category: '光',
    questionImage: 'images/light-fig2.png',
    question: '（図）は、2つの面が鏡A・Bになっている長方形の部屋を真上から見たようすです。点Xから鏡A上のある点に細い光をあてると、光は鏡A・Bではね返って点Yにとどきました。光をあてたのは、鏡Aの①〜⑤のうちのどの点ですか。',
    answer: '③',
    choices: ['③', '①', '②', '④', '⑤'],
  },
  {
    id: 'science-39',
    round: ROUND_1,
    category: '光',
    questionImage: 'images/light-enban-fig.png',
    question: '（図5）のように、円ばんと白い紙の距離を12cmから6cmに近づけました。このとき、白い紙にできる影はどうなりますか。点線は12cmのときにできた直径5cmの円形の影を示しています。',
    answer: 'images/light-enban-b.png',
    answerLabel: '影の大きさは変わらない（もとの5cmのまま）',
    choices: [
      'images/light-enban-a.png',
      'images/light-enban-b.png',
      'images/light-enban-c.png',
      'images/light-enban-d.png',
    ],
  },
  {
    id: 'science-40',
    round: ROUND_1,
    category: '光',
    questionImage: 'images/light-mushi-fig.png',
    question: '（図6）のように、虫めがねと白い紙の距離を12cmから6cmに近づけました。このとき、白い紙にできる明るい部分はどうなりますか。点線は12cmのときにできた直径5cmの円形の影を示しています。',
    answer: 'images/light-mushi-ki.png',
    answerLabel: '12cmのときより大きな明るい部分になる',
    choices: [
      'images/light-mushi-ka.png',
      'images/light-mushi-ki.png',
      'images/light-mushi-ku.png',
      'images/light-mushi-ke.png',
    ],
  },

  // ===== 4年上15回（組分けテスト③）: テーマ1 季節と生物・水・光 =====
  { id: 'sci3-01', round: ROUND_2, category: '春の生物', question: 'モンシロチョウのさなぎは、どうなると羽化しますか。', answer: 'あたたかくなると', choices: ['あたたかくなると', '寒くなると', '雨が降ると', '風が吹くと'] },
  { id: 'sci3-02', round: ROUND_2, category: '春の生物', question: '日本国内のモンシロチョウの初見日（成虫が初めて見られた日）は、季節が進むとどのように移っていきますか。', answer: '南から北へ', choices: ['南から北へ', '北から南へ', '東から西へ', '西から東へ'] },
  { id: 'sci3-03', round: ROUND_2, category: '春の生物', question: 'スズメのように、1年を通してほぼ同じ地域ですごす鳥を何といいますか。', answer: '留鳥', choices: ['留鳥', '夏鳥', '冬鳥', '漂鳥'] },
  { id: 'sci3-04', round: ROUND_2, category: '水のすがた', question: 'ゆげが白く見えるのは、水が何のすがたになっているためですか。', answer: '液体', choices: ['液体', '固体', '気体', 'プラズマ'] },
  { id: 'sci3-05', round: ROUND_2, category: '光', question: '「理」と書かれた厚紙を、上下が正しくなるように持ってかべの鏡にうつすと、どのように見えますか。', answer: '左右が反転して見える', choices: ['左右が反転して見える', '上下が反転して見える', 'そのまま同じに見える', '上下左右とも反転して見える'] },

  // ===== 4年上15回（組分けテスト③）: テーマ2 植物のつくりと育ち方 =====
  { id: 'sci3-06', round: ROUND_2, category: '植物', question: '次のうち、ふつう球根を植えてふやす植物としてあてはまらないものはどれですか。', answer: 'アジサイ', choices: ['アジサイ', 'ヒヤシンス', 'チューリップ', 'スイセン'] },
  { id: 'sci3-07', round: ROUND_2, category: '植物', question: 'ダイコン・キャベツ・コマツナは同じなかまの植物です。何科の植物ですか。', answer: 'アブラナ科', choices: ['アブラナ科', 'ウリ科', 'マメ科', 'キク科'] },
  { id: 'sci3-08', round: ROUND_2, category: '植物', question: 'ヘチマの種子の色や形として正しいのはどれですか。', answer: '黒くて平たい', choices: ['黒くて平たい', '白くて丸い', '緑色で三日月形', '茶色で細長い'] },
  { id: 'sci3-09', round: ROUND_2, category: '植物', question: 'ヘチマについての説明として正しいものはどれですか。', answer: 'お花とめ花の2種類の花をさかせる', choices: ['お花とめ花の2種類の花をさかせる', '花びらは4枚で、1枚ずつ取り外すことができる', '花粉はおもに風によって運ばれる', '1つの実に最大で6個の種子ができる'] },
  { id: 'sci3-10', round: ROUND_2, category: '植物', question: 'ヘチマはウリ科の植物です。次のうち、同じウリ科の植物はどれですか。', answer: 'カボチャ', choices: ['カボチャ', 'サツマイモ', 'ハクサイ', 'ジャガイモ'] },
  { id: 'sci3-11', round: ROUND_2, category: '植物', question: '植物のうち、子葉が1枚のグループを何といいますか。', answer: '単子葉類', choices: ['単子葉類', '双子葉類', '裸子植物', 'シダ植物'] },
  { id: 'sci3-12', round: ROUND_2, category: '植物', question: '単子葉類の根のようすとして正しいものはどれですか。', answer: 'ひげ根が広がる', choices: ['ひげ根が広がる', '太い根から枝分かれする', '根がない', '地中深くまで1本だけ伸びる'] },
  { id: 'sci3-13', round: ROUND_2, category: '植物', question: '植物が日光のエネルギーを利用して養分をつくるはたらきを何といいますか。', answer: '光合成', choices: ['光合成', '蒸散', '呼吸', '発芽'] },
  { id: 'sci3-14', round: ROUND_2, category: '植物', question: '光合成のとき、水とともに材料となる、空気中から取り入れる気体は何ですか。', answer: '二酸化炭素', choices: ['二酸化炭素', '酸素', 'ちっ素', '水素'] },
  { id: 'sci3-15', round: ROUND_2, category: '植物', question: '茎の維管束で、道管と師管のうち、内側にあるのはどちらですか。', answer: '道管', choices: ['道管', '師管', 'どちらも同じ位置にある', '決まっていない'] },
  { id: 'sci3-16', round: ROUND_2, category: '植物', question: '次のうち、双子葉類はどれですか。', answer: 'アサガオ', choices: ['アサガオ', 'イネ', 'トウモロコシ', 'ツユクサ'] },

  // ===== 4年上15回（組分けテスト③）: テーマ3 金属の性質 =====
  { id: 'sci3-17', round: ROUND_2, category: '金属', question: '多くの金属にあてはまる特ちょうとして、まちがっているものはどれですか。', answer: '磁石に引きつけられる', choices: ['磁石に引きつけられる', '電気や熱をよく伝える', 'たたいて板状にのばすことができる', '細く引きのばすことができる'] },
  { id: 'sci3-18', round: ROUND_2, category: '金属', question: 'とても軽く、さびに強いため、飲み物の缶などに使われる金属は何ですか。', answer: 'アルミニウム', choices: ['アルミニウム', '鉄', '銅', '銀'] },
  { id: 'sci3-19', round: ROUND_2, category: '金属', question: 'とけ始める温度が金属の中で最も高く、電気のエネルギーを光に変えやすいため電球のフィラメントに使われる金属は何ですか。', answer: 'タングステン', choices: ['タングステン', '鉄', '銅', '銀'] },
  { id: 'sci3-20', round: ROUND_2, category: '金属', question: '同じ太さ・長さのアルミニウム・銅・鉄の棒を束ねて同じ位置を加熱したとき、同じ距離につけたろうそくのマッチ棒が最も早く落ちるのはどの金属の棒ですか。', answer: '銅', choices: ['銅', 'アルミニウム', '鉄', 'どれも同時に落ちる'] },
  { id: 'sci3-21', round: ROUND_2, category: '金属', question: '熱が物の中を温度の高い方から低い方へ順に伝わっていく伝わり方を何といいますか。', answer: '伝導', choices: ['伝導', '対流', '放射', '蒸発'] },

  // ===== 4年上15回（組分けテスト③）: テーマ4 水と空気の温度と体積 =====
  { id: 'sci3-22', round: ROUND_2, category: '温度と体積', question: 'ヒトのからだにふくまれている水の重さは、からだ全体の重さの約何％ですか。', answer: '60~70%', choices: ['60~70%', '0~10%', '30~40%', '90~100%'] },
  { id: 'sci3-23', round: ROUND_2, category: '温度と体積', question: '空気1Lの重さを約1.3g、水1Lの重さを約1kgとして計算すると、同じ体積でくらべたとき、水の重さは空気の重さの約何倍になりますか（整数で）。', answer: '769倍', choices: ['769倍', '1300倍', '130倍', '77倍'] },
  { id: 'sci3-24', round: ROUND_2, category: '温度と体積', question: '水や空気の一部を加熱すると、あたためられた部分が上に移動し、上にあった部分と入れかわりながら全体があたたまっていきます。このようなあたたまり方を何といいますか。', answer: '対流', choices: ['対流', '伝導', '放射', '蒸発'] },
  { id: 'sci3-25', round: ROUND_2, category: '温度と体積', question: '水と空気をあたためたときの体積の変化について、正しい説明はどれですか。', answer: '水は体積がほとんど変わらないが、空気は体積が大きく変わる', choices: ['水は体積がほとんど変わらないが、空気は体積が大きく変わる', '水も空気も、体積が大きく変わる', '水は体積が大きく変わるが、空気は体積がほとんど変わらない', '水も空気も、体積がほとんど変わらない'] },
  { id: 'sci3-26', round: ROUND_2, category: '温度と体積', question: '20℃の水と空気を、それぞれ50℃にあたためたときの体積の増え方をくらべると、どうなりますか。', answer: '空気の方が水よりずっと大きく増える', choices: ['空気の方が水よりずっと大きく増える', '水の方が空気よりずっと大きく増える', 'どちらも同じくらい増える', 'どちらも変化しない'] },
  { id: 'sci3-27', round: ROUND_2, category: '温度と体積', question: '50℃の水と空気を、それぞれ20℃に冷やしたときの体積の減り方をくらべると、どうなりますか。', answer: '空気の方が水よりずっと大きく減る', choices: ['空気の方が水よりずっと大きく減る', '水の方が空気よりずっと大きく減る', 'どちらも同じくらい減る', 'どちらも変化しない'] },
  { id: 'sci3-28', round: ROUND_2, category: '温度と体積', question: '同じ容器に20℃の空気と50℃の空気を、それぞれいっぱいに入れてふたをしたとき、重さをくらべるとどうなりますか（容器の形や大きさは変化しないものとします）。', answer: '20℃の空気の方が重い', choices: ['20℃の空気の方が重い', '50℃の空気の方が重い', 'どちらも同じ重さになる', '比べられない'] },
];
